/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AgentForgeEscrow {
  export type MilestoneStruct = {
    description: string;
    amount: BigNumberish;
    receiver: AddressLike;
    status: BigNumberish;
    evidence: string;
    agentAddress: AddressLike;
  };

  export type MilestoneStructOutput = [
    description: string,
    amount: bigint,
    receiver: string,
    status: bigint,
    evidence: string,
    agentAddress: string
  ] & {
    description: string;
    amount: bigint;
    receiver: string;
    status: bigint;
    evidence: string;
    agentAddress: string;
  };

  export type EscrowContractStruct = {
    title: string;
    description: string;
    platform: AddressLike;
    serviceProvider: AddressLike;
    approver: AddressLike;
    disputeResolver: AddressLike;
    releaseSigner: AddressLike;
    status: BigNumberish;
    totalFunded: BigNumberish;
    totalReleased: BigNumberish;
    milestones: AgentForgeEscrow.MilestoneStruct[];
  };

  export type EscrowContractStructOutput = [
    title: string,
    description: string,
    platform: string,
    serviceProvider: string,
    approver: string,
    disputeResolver: string,
    releaseSigner: string,
    status: bigint,
    totalFunded: bigint,
    totalReleased: bigint,
    milestones: AgentForgeEscrow.MilestoneStructOutput[]
  ] & {
    title: string;
    description: string;
    platform: string;
    serviceProvider: string;
    approver: string;
    disputeResolver: string;
    releaseSigner: string;
    status: bigint;
    totalFunded: bigint;
    totalReleased: bigint;
    milestones: AgentForgeEscrow.MilestoneStructOutput[];
  };
}

export interface AgentForgeEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveMilestone"
      | "deployEscrow"
      | "escrowIds"
      | "escrows"
      | "fundEscrow"
      | "getEscrow"
      | "getMilestone"
      | "getMilestoneCount"
      | "getTotalBalance"
      | "markMilestone"
      | "owner"
      | "releaseMilestone"
      | "renounceOwnership"
      | "resolveDispute"
      | "startDispute"
      | "transferOwnership"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeResolved"
      | "DisputeStarted"
      | "EscrowDeployed"
      | "EscrowFunded"
      | "MilestoneApproved"
      | "MilestoneMarked"
      | "MilestoneReleased"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveMilestone",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployEscrow",
    values: [
      string,
      string,
      string,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AgentForgeEscrow.MilestoneStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "escrows", values: [string]): string;
  encodeFunctionData(
    functionFragment: "fundEscrow",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getEscrow", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getMilestone",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestoneCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalBalance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "markMilestone",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "releaseMilestone",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [string, BigNumberish, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "startDispute",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "approveMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrowIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fundEscrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMilestoneCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    escrowId: string,
    milestoneIndex: BigNumberish,
    receiver: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: string,
    milestoneIndex: bigint,
    receiver: string,
    amount: bigint
  ];
  export interface OutputObject {
    escrowId: string;
    milestoneIndex: bigint;
    receiver: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeStartedEvent {
  export type InputTuple = [escrowId: string, milestoneIndex: BigNumberish];
  export type OutputTuple = [escrowId: string, milestoneIndex: bigint];
  export interface OutputObject {
    escrowId: string;
    milestoneIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowDeployedEvent {
  export type InputTuple = [
    escrowId: string,
    title: string,
    platform: AddressLike
  ];
  export type OutputTuple = [escrowId: string, title: string, platform: string];
  export interface OutputObject {
    escrowId: string;
    title: string;
    platform: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowFundedEvent {
  export type InputTuple = [
    escrowId: string,
    funder: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [escrowId: string, funder: string, amount: bigint];
  export interface OutputObject {
    escrowId: string;
    funder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneApprovedEvent {
  export type InputTuple = [
    escrowId: string,
    milestoneIndex: BigNumberish,
    approver: AddressLike
  ];
  export type OutputTuple = [
    escrowId: string,
    milestoneIndex: bigint,
    approver: string
  ];
  export interface OutputObject {
    escrowId: string;
    milestoneIndex: bigint;
    approver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneMarkedEvent {
  export type InputTuple = [
    escrowId: string,
    milestoneIndex: BigNumberish,
    evidence: string
  ];
  export type OutputTuple = [
    escrowId: string,
    milestoneIndex: bigint,
    evidence: string
  ];
  export interface OutputObject {
    escrowId: string;
    milestoneIndex: bigint;
    evidence: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneReleasedEvent {
  export type InputTuple = [
    escrowId: string,
    milestoneIndex: BigNumberish,
    receiver: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: string,
    milestoneIndex: bigint,
    receiver: string,
    amount: bigint
  ];
  export interface OutputObject {
    escrowId: string;
    milestoneIndex: bigint;
    receiver: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentForgeEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): AgentForgeEscrow;
  waitForDeployment(): Promise<this>;

  interface: AgentForgeEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveMilestone: TypedContractMethod<
    [escrowId: string, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  deployEscrow: TypedContractMethod<
    [
      escrowId: string,
      title: string,
      description: string,
      platform: AddressLike,
      serviceProvider: AddressLike,
      approver: AddressLike,
      disputeResolver: AddressLike,
      releaseSigner: AddressLike,
      initialMilestones: AgentForgeEscrow.MilestoneStruct[]
    ],
    [void],
    "nonpayable"
  >;

  escrowIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  escrows: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        title: string;
        description: string;
        platform: string;
        serviceProvider: string;
        approver: string;
        disputeResolver: string;
        releaseSigner: string;
        status: bigint;
        totalFunded: bigint;
        totalReleased: bigint;
      }
    ],
    "view"
  >;

  fundEscrow: TypedContractMethod<
    [escrowId: string, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEscrow: TypedContractMethod<
    [escrowId: string],
    [AgentForgeEscrow.EscrowContractStructOutput],
    "view"
  >;

  getMilestone: TypedContractMethod<
    [escrowId: string, milestoneIndex: BigNumberish],
    [AgentForgeEscrow.MilestoneStructOutput],
    "view"
  >;

  getMilestoneCount: TypedContractMethod<[escrowId: string], [bigint], "view">;

  getTotalBalance: TypedContractMethod<[escrowId: string], [bigint], "view">;

  markMilestone: TypedContractMethod<
    [escrowId: string, milestoneIndex: BigNumberish, evidence: string],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  releaseMilestone: TypedContractMethod<
    [escrowId: string, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [
      escrowId: string,
      milestoneIndex: BigNumberish,
      receivers: AddressLike[],
      amounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  startDispute: TypedContractMethod<
    [escrowId: string, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveMilestone"
  ): TypedContractMethod<
    [escrowId: string, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployEscrow"
  ): TypedContractMethod<
    [
      escrowId: string,
      title: string,
      description: string,
      platform: AddressLike,
      serviceProvider: AddressLike,
      approver: AddressLike,
      disputeResolver: AddressLike,
      releaseSigner: AddressLike,
      initialMilestones: AgentForgeEscrow.MilestoneStruct[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "escrowIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        title: string;
        description: string;
        platform: string;
        serviceProvider: string;
        approver: string;
        disputeResolver: string;
        releaseSigner: string;
        status: bigint;
        totalFunded: bigint;
        totalReleased: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fundEscrow"
  ): TypedContractMethod<
    [escrowId: string, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [escrowId: string],
    [AgentForgeEscrow.EscrowContractStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMilestone"
  ): TypedContractMethod<
    [escrowId: string, milestoneIndex: BigNumberish],
    [AgentForgeEscrow.MilestoneStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMilestoneCount"
  ): TypedContractMethod<[escrowId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalBalance"
  ): TypedContractMethod<[escrowId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "markMilestone"
  ): TypedContractMethod<
    [escrowId: string, milestoneIndex: BigNumberish, evidence: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "releaseMilestone"
  ): TypedContractMethod<
    [escrowId: string, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [
      escrowId: string,
      milestoneIndex: BigNumberish,
      receivers: AddressLike[],
      amounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startDispute"
  ): TypedContractMethod<
    [escrowId: string, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeStarted"
  ): TypedContractEvent<
    DisputeStartedEvent.InputTuple,
    DisputeStartedEvent.OutputTuple,
    DisputeStartedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowDeployed"
  ): TypedContractEvent<
    EscrowDeployedEvent.InputTuple,
    EscrowDeployedEvent.OutputTuple,
    EscrowDeployedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowFunded"
  ): TypedContractEvent<
    EscrowFundedEvent.InputTuple,
    EscrowFundedEvent.OutputTuple,
    EscrowFundedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneApproved"
  ): TypedContractEvent<
    MilestoneApprovedEvent.InputTuple,
    MilestoneApprovedEvent.OutputTuple,
    MilestoneApprovedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneMarked"
  ): TypedContractEvent<
    MilestoneMarkedEvent.InputTuple,
    MilestoneMarkedEvent.OutputTuple,
    MilestoneMarkedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneReleased"
  ): TypedContractEvent<
    MilestoneReleasedEvent.InputTuple,
    MilestoneReleasedEvent.OutputTuple,
    MilestoneReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DisputeResolved(string,uint256,address,uint256)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "DisputeStarted(string,uint256)": TypedContractEvent<
      DisputeStartedEvent.InputTuple,
      DisputeStartedEvent.OutputTuple,
      DisputeStartedEvent.OutputObject
    >;
    DisputeStarted: TypedContractEvent<
      DisputeStartedEvent.InputTuple,
      DisputeStartedEvent.OutputTuple,
      DisputeStartedEvent.OutputObject
    >;

    "EscrowDeployed(string,string,address)": TypedContractEvent<
      EscrowDeployedEvent.InputTuple,
      EscrowDeployedEvent.OutputTuple,
      EscrowDeployedEvent.OutputObject
    >;
    EscrowDeployed: TypedContractEvent<
      EscrowDeployedEvent.InputTuple,
      EscrowDeployedEvent.OutputTuple,
      EscrowDeployedEvent.OutputObject
    >;

    "EscrowFunded(string,address,uint256)": TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;
    EscrowFunded: TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;

    "MilestoneApproved(string,uint256,address)": TypedContractEvent<
      MilestoneApprovedEvent.InputTuple,
      MilestoneApprovedEvent.OutputTuple,
      MilestoneApprovedEvent.OutputObject
    >;
    MilestoneApproved: TypedContractEvent<
      MilestoneApprovedEvent.InputTuple,
      MilestoneApprovedEvent.OutputTuple,
      MilestoneApprovedEvent.OutputObject
    >;

    "MilestoneMarked(string,uint256,string)": TypedContractEvent<
      MilestoneMarkedEvent.InputTuple,
      MilestoneMarkedEvent.OutputTuple,
      MilestoneMarkedEvent.OutputObject
    >;
    MilestoneMarked: TypedContractEvent<
      MilestoneMarkedEvent.InputTuple,
      MilestoneMarkedEvent.OutputTuple,
      MilestoneMarkedEvent.OutputObject
    >;

    "MilestoneReleased(string,uint256,address,uint256)": TypedContractEvent<
      MilestoneReleasedEvent.InputTuple,
      MilestoneReleasedEvent.OutputTuple,
      MilestoneReleasedEvent.OutputObject
    >;
    MilestoneReleased: TypedContractEvent<
      MilestoneReleasedEvent.InputTuple,
      MilestoneReleasedEvent.OutputTuple,
      MilestoneReleasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
